### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by Fiala06** [l3uddz/traktarr#124]
**Describe the bug**
Traktarr won't run anymore after adding a list. 

**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.imgur.com/4hi64QX.png

**Logs**
########################################################################
# Author:   l3uddz                                                      #
# URL:      https://github.com/l3uddz/traktarr                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################

Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 1675, in <module>
    app()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/traktarr", line 53, in app
    cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
  File "/traktarr/misc/config.py", line 131, in cfg
    tmp = self.load_config()
  File "/traktarr/misc/config.py", line 169, in load_config
    return AttrConfig(json.load(fp))
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 5 (char 540)
/traktarr # 

**System Information**

 - Traktarr Version: eafxx/traktarr:latest
 - Operating System: UNRAID 6.8.3 docker app

**Additional context**
Part of my config:

{
  "automatic": {
    "movies": {
      "anticipated": 1,
      "boxoffice": 10,
      "interval": 24,
      "popular": 1,
      "trending": 1
	      "lists": {
        "https://trakt.tv/users/tetharion/lists/worlds-of-dc": 3
    }
    },
    "shows": {
      "anticipated": 1,
      "interval": 72,
      "popular": 1,
      "trending": 1
    }
  },
  "core": {
    "debug": false
  },

**Comment by introvertmouse** [comment]
I am receiving the same error. Fresh Install of TRAKTARR today, CB been running great for weeks. Thank you for all the work you do.

**Comment by hawkash** [comment]
you need to put comma after `"trending": 1` in movie config

**Comment by Fiala06** [comment]
Thanks but still have the issue. Once I remove the lists it's fine.

Traceback (most recent call last):
File "traktarr.py", line 1675, in <module>


File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
Command.invoke(self, ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "traktarr.py", line 53, in app
cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
File "/traktarr/misc/config.py", line 131, in cfg
tmp = self.load_config()
File "/traktarr/misc/config.py", line 169, in load_config
return AttrConfig(json.load(fp))
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 20 column 4 (char 351)
for more info on the above run options: https://hub.docker.com/r/eafxx/traktarr

---------------------
| Starting Traktarr |
---------------------

[cont-init.d] 40-apprun: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.



"movies": {
      "anticipated": 1,
      "boxoffice": 10,
      "interval": 24,
      "popular": 1,
      "trending": 1,
	  "lists":{
      "https://trakt.tv/users/tetharion/lists/worlds-of-dc":3
	}
			  }
    },
