### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by palimpsest1** [l3uddz/traktarr#126]
**Describe the bug**
For some reason I can't use traktarr now, it always worked

**To Reproduce**
traktarr shows --ignore-blacklist -t '[link to my list here]'

**Expected behavior**
Adding episodes from trakt to sonarr, as always

**Logs**
Link to debug or trace log files.

___________              __      __                       
\__    ___/___________  |  | ___/  |______ ______________ 
  |    |  \_  __ \__  \ |  |/ /\   __\__  \\_  __ \_  __ \
  |    |   |  | \// __ \|    <  |  |  / __ \|  | \/|  | \/
  |____|   |__|  (____  /__|_ \ |__| (____  /__|   |__|   
                      \/     \/           \/              

#########################################################################
# Author:   l3uddz                                                      #
# URL:      https://github.com/l3uddz/traktarr                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################

Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 1675, in <module>
    app()
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/traktarr", line 53, in app
    cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
  File "/opt/traktarr/misc/config.py", line 131, in cfg
    tmp = self.load_config()
  File "/opt/traktarr/misc/config.py", line 169, in load_config
    return AttrConfig(json.load(fp))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 20 column 5 (char 343)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_traktarr_traktarr.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 1675, in <module>
    app()
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adrian/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/traktarr", line 53, in app
    cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
  File "/opt/traktarr/misc/config.py", line 131, in cfg
    tmp = self.load_config()
  File "/opt/traktarr/misc/config.py", line 169, in load_config
    return AttrConfig(json.load(fp))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 20 column 5 (char 343)

**System Information**

 - Traktarr Version: Master (latest)
 - Operating System: Linux Mint 19

**Comment by KINOTheProducer** [comment]
I am getting this issue currently in the logs - running as a docker in unRAID. Is there an update on this and how to fix it?

Thanks!

**Comment by codsane** [comment]
Probable that there is just some bad JSON in your config file, maybe run it through a [validator](https://jsonlint.com/) to confirm?
