### ISSUE TITLE
Watchlists non-functional

### ISSUE THREAD

**Issue by Xeckin** [l3uddz/traktarr#127]
Adding watchlists to the json file results in a python error.

Traceback (most recent call last):
File "traktarr.py", line 1675, in <module>

File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
Command.invoke(self, ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "traktarr.py", line 53, in app
cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
File "/traktarr/misc/config.py", line 131, in cfg
tmp = self.load_config()
File "/traktarr/misc/config.py", line 169, in load_config
return AttrConfig(json.load(fp))
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 13 (char 199)
for more info on the above run options: https://hub.docker.com/r/eafxx/traktarr

---------------------
| Starting Traktarr |
---------------------

[cont-init.d] 40-apprun: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by Xeckin** [comment]
{
    "automatic": {
        "movies": {
            "anticipated": "0",
            "boxoffice": "0",
            "interval": 15,
            "popular": "0",
            "trending": "0"
            "watchlist": {
                "mytraktusernam": 10,
            },
            "shows": {
                "anticipated": "0",
                "interval": 10,
                "popular": "0",
                "trending": "0"
                "watchlist": {
                    "mytraktusername": 10,
                }
            },
