### ISSUE TITLE
First run on Unraid issues.

### ISSUE THREAD

**Issue by NEprod** [l3uddz/traktarr#136]
On initial run using unraid I get the following error. I have set it up to just automatically search shows as per the read me placing interval for movies to 0 I have supplied my api for sonarr and correct ip I have also setup my trakt app and supplied both id and secret.

Traceback (most recent call last):
File "traktarr.py", line 1675, in <module>

File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
Command.invoke(self, ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "traktarr.py", line 53, in app
cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
File "/traktarr/misc/config.py", line 131, in cfg
tmp = self.load_config()
File "/traktarr/misc/config.py", line 169, in load_config
return AttrConfig(json.load(fp))
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 41 column 31 (char 913)
for more info on the above run options: https://hub.docker.com/r/eafxx/traktarr

**Comment by NEprod** [comment]
was config file error my bad had an extra , at the end of the trakt auth items.
