### ISSUE TITLE
Python Error - Any ideas?

### ISSUE THREAD

**Issue by joelang1699** [l3uddz/traktarr#153]
**Describe the bug**

Running the "traktarr trakt_authentication" command results in the following error

`___________ __ __
\__ ___/___________ | | ___/ |______ ______________
| | \_ __ \__ \ | |/ /\ __\__ \\_ __ \_ __ \
| | | | \// __ \| < | | / __ \| | \/| | \/
|____| |__| (____ /__|_ \ |__| (____ /__| |__|
\/ \/ \/

#########################################################################
# Author: l3uddz #
# URL: https://github.com/l3uddz/traktarr #
# -- #
# Part of the Cloudbox project: https://cloudbox.works #
#########################################################################
# GNU General Public License v3.0 #
#########################################################################

Traceback (most recent call last):
File "traktarr.py", line 1697, in <module>

File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
Command.invoke(self, ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "traktarr.py", line 52, in app
cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
File "/traktarr/misc/config.py", line 130, in cfg
tmp = self.load_config()
File "/traktarr/misc/config.py", line 168, in load_config
return AttrConfig(json.load(fp))
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 7 (char 148)
for more info on the above run options: https://hub.docker.com/r/eafxx/traktarr`

**System Information**

 - Traktarr Version: Latest
 - Operating System: Unraid 6.9.2 Docker

Any idea what's going wrong here?

**Comment by saltydk** [comment]
My initial guess would be that the config is setup incorrectly.

**Comment by joelang1699** [comment]
Ah right okay so it's something in the config and not a python issue.

I'll look over it again tomorrow.

⁣Cheers

**Comment by Wh1t3Rose** [comment]
I am having this issue as well. It seems it is caused by the Trak.TV list URLs. They now have a comma in the URL. This messes up the script

**Comment by joelang1699** [comment]
I haven't had a chance to try the script again, but I'll give this a go soon.
