### ISSUE TITLE
TypeError: movies() got an unexpected keyword argument 'year'

### ISSUE THREAD

**Issue by FLAFLALEBG** [l3uddz/traktarr#156]
**Describe the bug**
When I import any list (private / public) same as example : traktarr movies -t https://trakt.tv/users/rkerwin/lists/top-100-movies 
he return (full log):

___________              __      __                       
\__    ___/___________  |  | ___/  |______ ______________ 
  |    |  \_  __ \__  \ |  |/ /\   __\__  \\_  __ \_  __ \
  |    |   |  | \// __ \|    <  |  |  / __ \|  | \/|  | \/
  |____|   |__|  (____  /__|_ \ |__| (____  /__|   |__|   
                      \/     \/           \/              

#########################################################################
# Author:   l3uddz                                                      #
# URL:      https://github.com/l3uddz/traktarr                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################

Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 1697, in <module>
    app()
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
TypeError: movies() got an unexpected keyword argument 'year' 

Any idea for fix that ?

**Comment by Jamyn** [comment]
It seems like there are fundamental changes between **click 6.7** and later (ex: **click 8.0.3**). Try reinstalling 6.7 explicitly:

`sudo python -m pip install click==6.7`

I ran into similar issues trying to use Python 3.9. Python 3.7 worked fine.

**Comment by kazuiii** [comment]
same for me,
resintalling click 6.7 didn't change anything
