### ISSUE TITLE
traktarr.service error.

### ISSUE THREAD

**Issue by Landelor** [l3uddz/traktarr#59]
Hi team,

Getting this error when trying to run traktarr as a systemd service.

```Dec 07 20:12:11 LanBOX python3[38656]: 2018-12-07 20:12:11,148 - INFO       - traktarr                            - run                                 - Next job at None
Dec 07 20:12:11 LanBOX python3[38656]: 2018-12-07 20:12:11,149 - ERROR      - traktarr                            - run                                 - Unhandled exception occurred while processing scheduled tasks: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
Dec 07 20:12:11 LanBOX python3[38656]: Traceback (most recent call last):
Dec 07 20:12:11 LanBOX python3[38656]:   File "/opt/traktarr/traktarr.py", line 846, in run
Dec 07 20:12:11 LanBOX python3[38656]:     time.sleep(max(schedule.idle_seconds(), 0))
Dec 07 20:12:11 LanBOX python3[38656]:   File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 528, in idle_seconds
Dec 07 20:12:11 LanBOX python3[38656]:     return default_scheduler.idle_seconds
Dec 07 20:12:11 LanBOX python3[38656]:   File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 152, in idle_seconds
Dec 07 20:12:11 LanBOX python3[38656]:     return (self.next_run - datetime.datetime.now()).total_seconds()
Dec 07 20:12:11 LanBOX python3[38656]: TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'```

**Comment by desimaniac** [comment]
Can't have 0's for list limits in config.

**Comment by desimaniac** [comment]
Support for `0` interval has now been added in 86e33a8
