### ISSUE TITLE
ls

### ISSUE THREAD

**Issue by kaplannn** [l3uddz/traktarr#7]

**Comment by desimaniac** [comment]
Config looks OK. Tried running it as python3 (`python3 traktarr.py`)?

**Comment by kaplannn** [comment]
thanks for your reply :)

I tried it with python 3, same error.

Radarr is on nightly, sonarr is on master. I tried radarr with master, sonarr with develop, but nothing seems to work :/

I get the exact same error.

**Comment by l3uddz** [comment]
Turn debug logs on and paste the output pls. I know what the issue is but not sure why it's occuring for you and noone else.

**Comment by kaplannn** [comment]
Hi,

My quality profile is set to german. Thats the only thing that should not be equal to others.

Output:

> 
python3 traktarr.py movies -t trending -g comedy
2018-04-18 13:44:27,478 - DEBUG      - asyncio                             - __init__                            - Using selector: EpollSelector
2018-04-18 13:44:27,559 - DEBUG      - media.trakt                         - validate_api_key                    - Request Response: 200
2018-04-18 13:44:27,559 - INFO       - traktarr                            - movies                              - Validated Trakt API Key
2018-04-18 13:44:27,793 - DEBUG      - media.radarr                        - validate_api_key                    - Request Response: 200
2018-04-18 13:44:27,794 - INFO       - traktarr                            - movies                              - Validated Radarr URL & API Key
2018-04-18 13:44:27,935 - DEBUG      - media.radarr                        - get_profile_id                      - Request URL: XXX/radarr/api/profile
2018-04-18 13:44:27,935 - DEBUG      - media.radarr                        - get_profile_id                      - Request Response: 200
2018-04-18 13:44:27,935 - DEBUG      - media.radarr                        - get_profile_id                      - Profile Any with id 1 did not match GER - HD 720/1080
2018-04-18 13:44:27,935 - DEBUG      - media.radarr                        - get_profile_id                      - Profile SD with id 2 did not match GER - HD 720/1080
2018-04-18 13:44:27,935 - DEBUG      - media.radarr                        - get_profile_id                      - Profile HD-720p with id 3 did not match GER - HD 720/1080
2018-04-18 13:44:27,936 - DEBUG      - media.radarr                        - get_profile_id                      - Profile HD-1080p with id 4 did not match GER - HD 720/1080
2018-04-18 13:44:27,936 - DEBUG      - media.radarr                        - get_profile_id                      - Profile Ultra-HD with id 5 did not match GER - HD 720/1080
2018-04-18 13:44:27,936 - DEBUG      - media.radarr                        - get_profile_id                      - Profile HD - 720p/1080p with id 6 did not match GER - HD 720/1080
2018-04-18 13:44:27,936 - DEBUG      - media.radarr                        - get_profile_id                      - Found id of GER - HD 720/1080 profile: 7
2018-04-18 13:44:27,936 - INFO       - traktarr                            - movies                              - Retrieved Profile ID for GER - HD 720/1080: 7
2018-04-18 13:44:28,561 - DEBUG      - media.radarr                        - get_movies                          - Request URL: XXX/radarr/api/movie
2018-04-18 13:44:28,561 - DEBUG      - media.radarr                        - get_movies                          - Request Response: 200
2018-04-18 13:44:28,594 - DEBUG      - media.radarr                        - get_movies                          - Found 1323 movies
2018-04-18 13:44:28,594 - INFO       - traktarr                            - movies                              - Retrieved Radarr movies list, movies found: 1323
2018-04-18 13:44:29,597 - DEBUG      - media.trakt                         - get_trending_movies                 - Request URL: https://api.trakt.tv/movies/trending?limit=1000&extended=full&page=1&languages=en
2018-04-18 13:44:29,597 - DEBUG      - media.trakt                         - get_trending_movies                 - Request Payload: {'limit': 1000, 'extended': 'full', 'page': 1, 'languages': 'en'}
2018-04-18 13:44:29,598 - DEBUG      - media.trakt                         - get_trending_movies                 - Response Code: 200
2018-04-18 13:44:29,598 - DEBUG      - media.trakt                         - get_trending_movies                 - Response Page: 1 of 1
2018-04-18 13:44:29,607 - DEBUG      - media.trakt                         - get_trending_movies                 - There are no more pages to retrieve results from
2018-04-18 13:44:29,607 - DEBUG      - media.trakt                         - get_trending_movies                 - Found 404 trending movies
2018-04-18 13:44:29,607 - INFO       - traktarr                            - movies                              - Retrieved Trakt trending movies list, movies found: 404







2018-04-18 13:44:29,634 - INFO       - traktarr                            - movies                              - Adding: Step Sisters (2018) | Genres: comedy | Country: US
2018-04-18 13:44:30,599 - DEBUG      - media.radarr                        - add_movie                           - Request URL: XXX/radarr/api/movie
2018-04-18 13:44:30,600 - DEBUG      - media.radarr                        - add_movie                           - Request Payload: {'qualityProfileId': 7, 'minimumAvailability': 'released', 'tmdbId': 431072, 'year': 2018, 'rootFolderPath': '/home/plex/media/movies/', 'title': 'Step Sisters', 'images': [], 'addOptions': {'ignoreEpisodesWithFiles': False, 'searchForMovie': True, 'ignoreEpisodesWithoutFiles': False}, 'monitored': True, 'titleSlug': 'step-sisters-2018'}
2018-04-18 13:44:30,600 - DEBUG      - media.radarr                        - add_movie                           - Request Response: 200
2018-04-18 13:44:30,636 - ERROR      - media.radarr                        - add_movie                           - Exception adding movie Step Sisters (431072):
Traceback (most recent call last):
  File "/opt/traktarr/media/radarr.py", line 98, in add_movie
    if (req.status_code == 201 or req.status_code == 200) and req.json()['tmdbId'] == movie_tmdbid:
TypeError: list indices must be integers or slices, not str
2018-04-18 13:44:30,637 - WARNING    - media.radarr                        - backoff_handler                     - Backing off 1.0 seconds afters 1 tries calling function <function Radarr.add_movie at 0x7f5e56aaad08> with args (<media.radarr.Radarr object at 0x7f5e5a857be0>, 431072, 'Step Sisters', 2018, 'step-sisters-2018', 7, '/home/plex/media/movies/', True) and kwargs {}
2018-04-18 13:44:32,170 - DEBUG      - media.radarr                        - add_movie                           - Request URL: XXX/radarr/api/movie
2018-04-18 13:44:32,170 - DEBUG      - media.radarr                        - add_movie                           - Request Payload: {'qualityProfileId': 7, 'minimumAvailability': 'released', 'tmdbId': 431072, 'year': 2018, 'rootFolderPath': '/home/plex/media/movies/', 'title': 'Step Sisters', 'images': [], 'addOptions': {'ignoreEpisodesWithFiles': False, 'searchForMovie': True, 'ignoreEpisodesWithoutFiles': False}, 'monitored': True, 'titleSlug': 'step-sisters-2018'}
2018-04-18 13:44:32,170 - DEBUG      - media.radarr                        - add_movie                           - Request Response: 200
2018-04-18 13:44:32,210 - ERROR      - media.radarr                        - add_movie                           - Exception adding movie Step Sisters (431072):
Traceback (most recent call last):
  File "/opt/traktarr/media/radarr.py", line 98, in add_movie
    if (req.status_code == 201 or req.status_code == 200) and req.json()['tmdbId'] == movie_tmdbid:
TypeError: list indices must be integers or slices, not str
2018-04-18 13:44:32,210 - WARNING    - media.radarr                        - backoff_handler                     - Backing off 0.9 seconds afters 2 tries calling function <function Radarr.add_movie at 0x7f5e56aaad08> with args (<media.radarr.Radarr object at 0x7f5e5a857be0>, 431072, 'Step Sisters', 2018, 'step-sisters-2018', 7, '/home/plex/media/movies/', True) and kwargs {}
2018-04-18 13:44:33,695 - DEBUG      - media.radarr                        - add_movie                           - Request URL: XXX/radarr/api/movie
2018-04-18 13:44:33,695 - DEBUG      - media.radarr                        - add_movie                           - Request Payload: {'qualityProfileId': 7, 'minimumAvailability': 'released', 'tmdbId': 431072, 'year': 2018, 'rootFolderPath': '/home/plex/media/movies/', 'title': 'Step Sisters', 'images': [], 'addOptions': {'ignoreEpisodesWithFiles': False, 'searchForMovie': True, 'ignoreEpisodesWithoutFiles': False}, 'monitored': True, 'titleSlug': 'step-sisters-2018'}
2018-04-18 13:44:33,696 - DEBUG      - media.radarr                        - add_movie                           - Request Response: 200
2018-04-18 13:44:33,734 - ERROR      - media.radarr                        - add_movie                           - Exception adding movie Step Sisters (431072):
Traceback (most recent call last):
  File "/opt/traktarr/media/radarr.py", line 98, in add_movie
    if (req.status_code == 201 or req.status_code == 200) and req.json()['tmdbId'] == movie_tmdbid:
TypeError: list indices must be integers or slices, not str
2018-04-18 13:44:33,734 - WARNING    - media.radarr                        - backoff_handler                     - Backing off 3.8 seconds afters 3 tries calling function <function Radarr.add_movie at 0x7f5e56aaad08> with args (<media.radarr.Radarr object at 0x7f5e5a857be0>, 431072, 'Step Sisters', 2018, 'step-sisters-2018', 7, '/home/plex/media/movies/', True) and kwargs {}
2018-04-18 13:44:38,123 - DEBUG      - media.radarr                        - add_movie                           - Request URL: XXX/radarr/api/movie
2018-04-18 13:44:38,124 - DEBUG      - media.radarr                        - add_movie                           - Request Payload: {'qualityProfileId': 7, 'minimumAvailability': 'released', 'tmdbId': 431072, 'year': 2018, 'rootFolderPath': '/home/plex/media/movies/', 'title': 'Step Sisters', 'images': [], 'addOptions': {'ignoreEpisodesWithFiles': False, 'searchForMovie': True, 'ignoreEpisodesWithoutFiles': False}, 'monitored': True, 'titleSlug': 'step-sisters-2018'}
2018-04-18 13:44:38,124 - DEBUG      - media.radarr                        - add_movie                           - Request Response: 200
2018-04-18 13:44:38,157 - ERROR      - media.radarr                        - add_movie                           - Exception adding movie Step Sisters (431072):
Traceback (most recent call last):
  File "/opt/traktarr/media/radarr.py", line 98, in add_movie
    if (req.status_code == 201 or req.status_code == 200) and req.json()['tmdbId'] == movie_tmdbid:
TypeError: list indices must be integers or slices, not str
2018-04-18 13:44:38,157 - ERROR      - backoff                             - _log_giveup                         - Giving up add_movie(...) after 4 tries (None)
2018-04-18 13:44:38,157 - ERROR      - traktarr                            - movies                              - FAILED adding Step Sisters (2018)


Cheers

**Comment by l3uddz** [comment]
Is the movie being added? It just fails to recognise it as successful?

**Comment by kaplannn** [comment]
Unfortunately it's not beeing added ):

**Comment by l3uddz** [comment]
I pushed a change to develop branch that should help further diagnose the issue + detect bad responses.
Please do

```git fetch
git reset --hard origin/develop```

Then try running another add and paste the entire log to paste.ee if the error continues

**Comment by kaplannn** [comment]
i tried it with de develop branch. Same Error.

If i enable debug-logging. it will create 3 log files, each 3.4M, cause it lists every movie i have in radarr.

https://paste.ee/p/cZigb
https://paste.ee/p/TgCmF

Do you need a more specific log?

**Comment by l3uddz** [comment]
I need to see what the response text is. Pls put up the add movies part including the response text

**Comment by kaplannn** [comment]
https://paste.ee/p/QFs3w

Ok i guess the response text is then all the movie infos in radarr.

**Comment by l3uddz** [comment]
have pushed a change, pls follow the same procedure above with git and let me know if that solves the problem.

**Comment by l3uddz** [comment]
Must admit, I am not sure why you are seeing a response of Lord of the Rings being added, when the add request was for When We First Met.

Are you sure there is not another traktarr running? 

```ps aux | grep traktarr```

**Comment by kaplannn** [comment]
did that. same error ):

yeah i don't get that either. The thing is, for every movie foun on trakt, it will respond with every movie in radarr. So "Lord of the rings" as you see in the log, is only 1 movie from 1300 (log will be too big to paste due to 1300 movie entries as a response text).

There is no other process running.

**Comment by l3uddz** [comment]
turn debug log off.

remove the .log files and run for example

```python3 traktarr.py movies -t trending -l 2```

Please give me the full output for that (no debug log)

**Comment by kaplannn** [comment]
it's responding with all movies aswell, debug log off:

https://paste.ee/p/VVUhE

**Comment by l3uddz** [comment]
well im stumped.

i will update my radarr later and do some further testing. but it looks like radarr is returning the entire movie list when adding a new movie. this doesnt happen with the current version im using ```
Radarr Ver. 0.2.0.1047
nightly
```

Does sonarr add fine?

**Comment by kaplannn** [comment]
Same behaviour with Sonarr.

Radarr Ver. 0.2.0.1067
nightly

Sonarr Ver. 2.0.0.5169
master

I removed and "installed" the whole traktarr source from develop branch. Still the same error with the response of all movies/shows. 

This is kinda strange :D

**Comment by l3uddz** [comment]
well, im not sure then... its working fine for me on the latest sonarr.

are you using a reverse proxy? or is there any reason why post requests arent going through to them?

**Comment by kaplannn** [comment]
yeah i am using nginx. gonna check that. But i really appreciate your support, thanks bud!

**Comment by l3uddz** [comment]
Np, most likely there's an issue there that is causing this to fail.

**Comment by l3uddz** [comment]
could you git pull and try the latest develop out?

it should fix your issue thanks to a recent PR from another contributor who was having the same issue.

**Comment by kaplannn** [comment]
Hi,

I tried it, still exactly the same behaviour. i changed my config file to this:

"url": "https://subdomain.domain.com/"

**Comment by l3uddz** [comment]
If you have pulled the latest changes, the issue that was causing that to happen was fixed. Really unsure what else to suggest other than checking nginx configs.

**Comment by kaplannn** [comment]
Yeah i removed everything, tried it from beginning: traktarr, version 1.1.3

The config File will not be created anymore, after you launch "traktarr" for the first time.

Proxy seems to be good. I have no clue what the problem is :/ Anyway, thank you!

**Comment by l3uddz** [comment]
Try running a command, e.g. traktarr shows -t trending -l 1 and it should generate the default config

**Comment by kaplannn** [comment]
I got it working.

I set up a Base-URL within Sonarr and Radarr. i had to add the Base-URL to the config file
"https://sub.domain.com/sonarr/"

Thank you guys 😃

**Comment by l3uddz** [comment]
Glad you got it working!

**Comment by mouzzampk2014** [comment]
> I got it working.
> I set up a Base-URL within Sonarr and Radarr. i had to add the Base-URL to the config file
> "https://sub.domain.com/sonarr/"
> Thank you guys 😃

Hi, I am exactly done same thing but shows are not adding into my sonarr:preview. Any help :)
