### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by iksajsad** [l3uddz/traktarr#70]
I'm getting this error when I try to run pgtrakt:

`obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 758775 (char 758774)
2019-04-20 17:59:32,260 - WARNING    - helpers.misc                        - backoff_handler                     - Backing off 0.6 seconds afters 2 tries calling function <function Trakt._make_items_request at 0x7f4c72c9ea60> with args (<media.trakt.Trakt object at 0x7f4c751264e0>,) and kwargs {'url': 'https://api.trakt.tv/movies/played/all', 'limit': 1000, 'languages': (), 'object_name': 'movies', 'type_name': 'played', 'genres': None}
2019-04-20 17:59:32,854 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:32,927 - INFO       - media.trakt                         - _make_items_request                 - There are 131 pages left to retrieve results from
2019-04-20 17:59:37,932 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:38,054 - INFO       - media.trakt                         - _make_items_request                 - There are 130 pages left to retrieve results from
2019-04-20 17:59:43,058 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:43,240 - INFO       - media.trakt                         - _make_items_request                 - There are 129 pages left to retrieve results from
2019-04-20 17:59:48,246 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:48,312 - ERROR      - media.trakt                         - _make_items_request                 - Exception retrieving played movies:
Traceback (most recent call last):
  File "/opt/appdata/pgtrakt/media/trakt.py", line 87, in _make_items_request
    resp_json = req.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 758775 (char 758774)
2019-04-20 17:59:48,319 - WARNING    - helpers.misc                        - backoff_handler                     - Backing off 0.4 seconds afters 3 tries calling function <function Trakt._make_items_request at 0x7f4c72c9ea60> with args (<media.trakt.Trakt object at 0x7f4c751264e0>,) and kwargs {'url': 'https://api.trakt.tv/movies/played/all', 'limit': 1000, 'languages': (), 'object_name': 'movies', 'type_name': 'played', 'genres': None}
2019-04-20 17:59:48,720 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:48,799 - INFO       - media.trakt                         - _make_items_request                 - There are 131 pages left to retrieve results from
2019-04-20 17:59:53,804 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:53,923 - INFO       - media.trakt                         - _make_items_request                 - There are 130 pages left to retrieve results from
2019-04-20 17:59:58,928 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 17:59:59,109 - INFO       - media.trakt                         - _make_items_request                 - There are 129 pages left to retrieve results from
2019-04-20 18:00:04,115 - INFO       - media.trakt                         - _headers                            - No user
2019-04-20 18:00:04,176 - ERROR      - media.trakt                         - _make_items_request                 - Exception retrieving played movies:
Traceback (most recent call last):
  File "/opt/appdata/pgtrakt/media/trakt.py", line 87, in _make_items_request
    resp_json = req.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 758775 (char 758774)
2019-04-20 18:00:04,185 - ERROR      - backoff                             - _log_giveup                         - Giving up _make_items_request(...) after 4 tries (None)
2019-04-20 18:00:04,186 - ERROR      - pgtrack                             - movies                              - Aborting due to failure to retrieve Trakt played_all movies list`

Any idea whats wrong here?

**Comment by desimaniac** [comment]
JSON format issue. https://jsonformatter.curiousconcept.com/
