### ISSUE TITLE
Cannot run Traktarr

### ISSUE THREAD

**Issue by hitmancho** [l3uddz/traktarr#98]
I am using Raspberry Pi 4 with everything updated. I followed the instructions to install by the letter and did some setting up to my /opt/traktarr/config.json. After that I created the automatic script and rebooted the Pi. When I try "traktarr run" I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 1291, in <module>
    app()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/traktarr", line 52, in app
    cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
  File "/opt/traktarr/misc/config.py", line 127, in cfg
    tmp = self.load_config()
  File "/opt/traktarr/misc/config.py", line 165, in load_config
    return AttrConfig(json.load(fp))
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 29 column 31 (char 532)

Seems like a python issue but I have no idea what this all means... I double checked if I had installed python and all the requirements + all user permissions.

**Comment by desimaniac** [comment]
It's a config issue. 

```
json.decoder.JSONDecodeError: Expecting value: line 29 column 31 (char 532)
```

Check and fix your config at https://jsonformatter.curiousconcept.com/

**Comment by hitmancho** [comment]
Yes, it was... The editor was showing "[]" at one place but there was nothing. Weird, but it got it fixed. Thank you for the link.
